name: FwkIO
namespace: FwkIO
title: fwk.io website
description: The home of Fwk
homepage: home
errorpage: error
directories: 
    pages: ./pages
    sources: ../FwkIO
    assets: ./assets
    forms: ./forms
    cache: ../../cache
    config: ./config
domain:
    name: fwk.io
    force: true
config: ~
services:
    - ./services.xml
urls:
    "/:package/:version/api/:type/:className.html$":
        page: package/apidoc-class
        parameters:
            package:
                required: true
                regex: core|db|di|xml|form|cache|events|Core|Db|Di|Xml|Form|Cache|Events
            version:
                required: true
                default: master
            type:
                required: true
                regex: class|interface
            className:
                required: true
                regex: .*
    "/:package/:version/api$":
            page: package/apidoc
            parameters:
                package:
                    required: true
                    regex: core|db|di|xml|form|cache|events|Core|Db|Di|Xml|Form|Cache|Events
                version:
                    required: false
                    default: master
    "/:package/:version/doc/:docPage$":
            page: package/doc
            parameters:
                package:
                    required: true
                    regex: core|db|di|xml|form|cache|events|Core|Db|Di|Xml|Form|Cache|Events
                version:
                    required: false
                    default: master
                docPage:
                    required: true
                    regex: .*
    "/:package/:version/doc$":
            page: package/doc
            parameters:
                package:
                    required: true
                    regex: core|db|di|xml|form|cache|events|Core|Db|Di|Xml|Form|Cache|Events
                version:
                    required: false
                    default: master
    "/:package/:version/status$":
                page: package/status
                parameters:
                    package:
                        required: true
                        regex: core|db|di|xml|form|cache|events|Core|Db|Di|Xml|Form|Cache|Events
                    version:
                        required: false
                        default: master
    "/:package$":
            page: package/intro
            parameters:
                package:
                    required: true
                    regex: core|db|di|xml|form|cache|events|Core|Db|Di|Xml|Form|Cache|Events
    "/:package/:version$":
        page: package/intro
        parameters:
            package:
                required: true
                regex: core|db|di|xml|form|cache|events|Core|Db|Di|Xml|Form|Cache|Events
            version:
                required: false
                default: master
    "/:page$":
        parameters:
            page:
                required: false
                regex: .*
page_config:
    active: true
    cache:
        public: true
        enable: false
        lifetime: 86400
    config: ~
    listeners: ~
    defaults: ~
    datasources:
        packages: 
            class: FwkIO\CMF\FwkPackagesDataSource
            #service: serviceName
            constructor:
                - :packageDir/fwk-packages.xml
                - @fwk.cache